### ISSUE TITLE
Error when running gacServer

### ISSUE THREAD

**Issue by shishir167** [DrexelChatbotGroup/DrexelChatbot#19]
File "gacServer.py", line 45, in loadAnswers
    d[int(fields[0])] = GenericAnswer(fields[1], fields[2])
ValueError: invalid literal for int() with base 10: '\ufeff0'
Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7fb56980e748>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 582, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus'

**Comment by incherre** [comment]
There are two different errors in this copy-paste. The first is caused because there is a Unicode character at the beginning of the genericAnswers.csv file that is optional in utf-8 encoding. I think we can just delete it, but I'll also add some code to ensure that the gacServer is more robust to this type of error.

**Comment by incherre** [comment]
Fixing the first error got rid of the second too.
